---
- name: Add user to Group
  hosts: web01
  become: yes

  vars_prompt:
    - name: target_user
      prompt: "Enter the username:"

  tasks:
    - name: Check if the user exists
      command: id "{{ target_user }}"
      register: user_check
      ignore_errors: true

    - name: Inform user if already exists
      debug:
        msg: "User {{ target_user }} already exists."
      when: user_check.rc == 0

    - name: Check if group already exists
      command: getent group freshgroup
      register: group_check
      ignore_errors: true

    - name: Create new group if not exists
      ansible.builtin.group:
        name: freshgroup
        state: present
      when: group_check.rc != 0
      notify: create_group

    - name: Add user if new
      ansible.builtin.user:
        name: "{{ target_user }}"
        state: present
        groups: "freshgroup"
      when: user_check.rc != 0
      notify: add_user

  handlers:
    - name: add_user
      ansible.builtin.user:
        name: "{{ target_user }}"

    - name: create_group
      ansible.builtin.group:
        name: freshgroup
        state: present
