- name: Add user to Group
  hosts: web01
  become: yes

  tasks:
    - name: Prompt for username
      ansible.builtin.vars_prompt:
        name: target_user
        prompt: "Enter the username: "

    - name: Prompt for password
      ansible.builtin.password:
        prompt: "Enter the password: "
      register: user_password

    - name: Check if the user exists
      ansible.builtin.getent:
        database: passwd
        key: "{{ target_user }}"
      register: user_check
      ignore_errors: true

    - name: Inform user if already exists
      debug:
        msg: "User {{ target_user }} already exists."
      when: user_check.failed == false

    - name: Create new group
      ansible.builtin.group:
        name: freshgroup
        state: present

    - name: Add user if new
      ansible.builtin.user:
        name: "{{ target_user }}"
        password: "{{ user_password.stdout }}"
        state: present
        groups: "freshgroup"
      when: user_check.failed == true
      notify: add_user

  handlers:
    - name: add_user
      ansible.builtin.user:
        name: "{{ target_user }}"
        password: "{{ user_password.stdout }}"
