apiVersion: apps/v1
kind: Deployment
metadata:
  name: addingusers-deployment
  labels:
    app: addingUsers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: addingusers
  template:
    metadata:
      labels:
        app: addingusers
    spec:
      containers:
        - name: addingusers
          image: oronops/adding-users-image:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: Always
